#!/bin/sh
# This script adds "Reboot" and "Shutdown" menu entries to GRUB.
# Make executable by running sudo chmod +x /etc/grub.d/40_reboot_shutdown
# Place in /etc/grub.d

echo "Adding boot menu entries for Reboot and Shutdown ...\n" >&2

exec tail -n +9 $0

menuentry 'Reboot' \$menuentry_id_option 'Reboot' {
    reboot
}
menuentry 'Shutdown' \$menuentry_id_option 'Shutdown' {
    halt
}
